window.HANZI_DATASETS = {
  hsk1: [
    {"hanzi": "一", "pinyin": "yī", "definition": "one"},
    {"hanzi": "二", "pinyin": "èr", "definition": "two"},
    {"hanzi": "三", "pinyin": "sān", "definition": "three"},
    {"hanzi": "四", "pinyin": "sì", "definition": "four"},
    {"hanzi": "五", "pinyin": "wǔ", "definition": "five"},
    {"hanzi": "六", "pinyin": "liù", "definition": "six"},
    {"hanzi": "七", "pinyin": "qī", "definition": "seven"},
    {"hanzi": "八", "pinyin": "bā", "definition": "eight"},
    {"hanzi": "九", "pinyin": "jiǔ", "definition": "nine"},
    {"hanzi": "十", "pinyin": "shí", "definition": "ten"},
    {"hanzi": "人", "pinyin": "rén", "definition": "person, people"},
    {"hanzi": "大", "pinyin": "dà", "definition": "big, large"},
    {"hanzi": "小", "pinyin": "xiǎo", "definition": "small, little"},
    {"hanzi": "我", "pinyin": "wǒ", "definition": "I, me"},
    {"hanzi": "你", "pinyin": "nǐ", "definition": "you"},
    {"hanzi": "他", "pinyin": "tā", "definition": "he, him"},
    {"hanzi": "她", "pinyin": "tā", "definition": "she, her"},
    {"hanzi": "我们", "pinyin": "wǒmen", "definition": "we, us"},
    {"hanzi": "好", "pinyin": "hǎo", "definition": "good, well"},
    {"hanzi": "爱", "pinyin": "ài", "definition": "to love, affection"},
    {"hanzi": "吃", "pinyin": "chī", "definition": "to eat"},
    {"hanzi": "喝", "pinyin": "hē", "definition": "to drink"},
    {"hanzi": "看", "pinyin": "kàn", "definition": "to see, look, read"},
    {"hanzi": "听", "pinyin": "tīng", "definition": "to listen, hear"},
    {"hanzi": "说话", "pinyin": "shuōhuà", "definition": "to speak, talk"},
    {"hanzi": "读", "pinyin": "dú", "definition": "to read"},
    {"hanzi": "写", "pinyin": "xiě", "definition": "to write"},
    {"hanzi": "学习", "pinyin": "xuéxí", "definition": "to study, learn"},
    {"hanzi": "学校", "pinyin": "xuéxiào", "definition": "school"},
    {"hanzi": "学生", "pinyin": "xuésheng", "definition": "student"},
    {"hanzi": "老师", "pinyin": "lǎoshī", "definition": "teacher"},
    {"hanzi": "朋友", "pinyin": "péngyou", "definition": "friend"},
    {"hanzi": "医生", "pinyin": "yīshēng", "definition": "doctor"},
    {"hanzi": "家", "pinyin": "jiā", "definition": "home, family"},
    {"hanzi": "中国", "pinyin": "Zhōngguó", "definition": "China"},
    {"hanzi": "爸爸", "pinyin": "bàba", "definition": "father, dad"},
    {"hanzi": "妈妈", "pinyin": "māma", "definition": "mother, mom"},
    {"hanzi": "儿子", "pinyin": "érzi", "definition": "son"},
    {"hanzi": "女儿", "pinyin": "nǚ'ér", "definition": "daughter"},
    {"hanzi": "水", "pinyin": "shuǐ", "definition": "water"},
    {"hanzi": "茶", "pinyin": "chá", "definition": "tea"},
    {"hanzi": "米饭", "pinyin": "mǐfàn", "definition": "cooked rice"},
    {"hanzi": "水果", "pinyin": "shuǐguǒ", "definition": "fruit"},
    {"hanzi": "苹果", "pinyin": "píngguǒ", "definition": "apple"},
    {"hanzi": "猫", "pinyin": "māo", "definition": "cat"},
    {"hanzi": "狗", "pinyin": "gǒu", "definition": "dog"},
    {"hanzi": "飞机", "pinyin": "fēijī", "definition": "airplane"},
    {"hanzi": "出租车", "pinyin": "chūzūchē", "definition": "taxi"},
    {"hanzi": "钱", "pinyin": "qián", "definition": "money"},
    {"hanzi": "名字", "pinyin": "míngzi", "definition": "name"},
    {"hanzi": "谢谢", "pinyin": "xièxie", "definition": "thank you"},
    {"hanzi": "不客气", "pinyin": "bú kèqi", "definition": "you're welcome"},
    {"hanzi": "再见", "pinyin": "zàijiàn", "definition": "goodbye"},
    {"hanzi": "对不起", "pinyin": "duìbuqǐ", "definition": "sorry"},
    {"hanzi": "没关系", "pinyin": "méi guānxi", "definition": "it doesn't matter"},
    {"hanzi": "是", "pinyin": "shì", "definition": "to be, yes"},
    {"hanzi": "不", "pinyin": "bù", "definition": "not, no"},
    {"hanzi": "有", "pinyin": "yǒu", "definition": "to have"},
    {"hanzi": "没有", "pinyin": "méiyǒu", "definition": "to not have"},
    {"hanzi": "多", "pinyin": "duō", "definition": "many, much"},
    {"hanzi": "少", "pinyin": "shǎo", "definition": "few, little"},
    {"hanzi": "高兴", "pinyin": "gāoxìng", "definition": "happy, glad"},
    {"hanzi": "上", "pinyin": "shàng", "definition": "above, up"},
    {"hanzi": "下", "pinyin": "xià", "definition": "below, down"},
    {"hanzi": "里", "pinyin": "lǐ", "definition": "inside"},
    {"hanzi": "今天", "pinyin": "jīntiān", "definition": "today"},
    {"hanzi": "明天", "pinyin": "míngtiān", "definition": "tomorrow"},
    {"hanzi": "昨天", "pinyin": "zuótiān", "definition": "yesterday"},
    {"hanzi": "年", "pinyin": "nián", "definition": "year"},
    {"hanzi": "月", "pinyin": "yuè", "definition": "month"},
    {"hanzi": "日", "pinyin": "rì", "definition": "day, date"}
  ],
  hsk2: [
    {"hanzi": "吧", "pinyin": "ba", "definition": "suggestion particle"},
    {"hanzi": "白", "pinyin": "bái", "definition": "white, pure"},
    {"hanzi": "百", "pinyin": "bǎi", "definition": "hundred"},
    {"hanzi": "帮助", "pinyin": "bāngzhù", "definition": "to help, assist"},
    {"hanzi": "报纸", "pinyin": "bàozhǐ", "definition": "newspaper"},
    {"hanzi": "比", "pinyin": "bǐ", "definition": "compare, than"},
    {"hanzi": "别", "pinyin": "bié", "definition": "don't, other"},
    {"hanzi": "长", "pinyin": "cháng", "definition": "long"},
    {"hanzi": "唱歌", "pinyin": "chànggē", "definition": "to sing a song"},
    {"hanzi": "穿", "pinyin": "chuān", "definition": "to wear, put on"},
    {"hanzi": "次", "pinyin": "cì", "definition": "time, occurrence"},
    {"hanzi": "从", "pinyin": "cóng", "definition": "from"},
    {"hanzi": "错", "pinyin": "cuò", "definition": "wrong, mistake"},
    {"hanzi": "篮球", "pinyin": "lánqiú", "definition": "basketball"},
    {"hanzi": "大家", "pinyin": "dàjiā", "definition": "everyone"},
    {"hanzi": "到", "pinyin": "dào", "definition": "to arrive, reach"},
    {"hanzi": "等", "pinyin": "děng", "definition": "to wait"},
    {"hanzi": "弟弟", "pinyin": "dìdi", "definition": "younger brother"},
    {"hanzi": "第一", "pinyin": "dì-yī", "definition": "first, number one"},
    {"hanzi": "懂", "pinyin": "dǒng", "definition": "to understand"},
    {"hanzi": "房间", "pinyin": "fángjiān", "definition": "room"},
    {"hanzi": "非常", "pinyin": "fēicháng", "definition": "very, extremely"},
    {"hanzi": "服务员", "pinyin": "fúwùyuán", "definition": "waiter, attendant"},
    {"hanzi": "高", "pinyin": "gāo", "definition": "tall, high"},
    {"hanzi": "告诉", "pinyin": "gàosu", "definition": "to tell, inform"},
    {"hanzi": "哥哥", "pinyin": "gēge", "definition": "older brother"},
    {"hanzi": "给", "pinyin": "gěi", "definition": "to give"},
    {"hanzi": "公共汽车", "pinyin": "gōnggòng qìchē", "definition": "bus"},
    {"hanzi": "公司", "pinyin": "gōngsī", "definition": "company, office"},
    {"hanzi": "贵", "pinyin": "guì", "definition": "expensive, noble"}
  ],
  hsk3: [
    {"hanzi": "阿姨", "pinyin": "āyí", "definition": "aunt, housekeeper"},
    {"hanzi": "矮", "pinyin": "ǎi", "definition": "short (height)"},
    {"hanzi": "爱好", "pinyin": "àihào", "definition": "hobby, interest"},
    {"hanzi": "安静", "pinyin": "ānjìng", "definition": "quiet, peaceful"},
    {"hanzi": "把", "pinyin": "bǎ", "definition": "hold, particle for object disposal"},
    {"hanzi": "搬", "pinyin": "bān", "definition": "to move, carry"},
    {"hanzi": "办法", "pinyin": "bànfǎ", "definition": "method, way, solution"},
    {"hanzi": "办公室", "pinyin": "bàngōngshì", "definition": "office"},
    {"hanzi": "半", "pinyin": "bàn", "definition": "half"},
    {"hanzi": "帮忙", "pinyin": "bāngmáng", "definition": "to help, do a favor"},
    {"hanzi": "包", "pinyin": "bāo", "definition": "bag, package, wrap"},
    {"hanzi": "饱", "pinyin": "bǎo", "definition": "full (from eating)"},
    {"hanzi": "北方", "pinyin": "běifāng", "definition": "north, northern region"},
    {"hanzi": "被", "pinyin": "bèi", "definition": "by (passive voice particle)"},
    {"hanzi": "鼻子", "pinyin": "bízi", "definition": "nose"},
    {"hanzi": "比赛", "pinyin": "bǐsài", "definition": "match, competition"},
    {"hanzi": "变化", "pinyin": "biànhuà", "definition": "change, variation"},
    {"hanzi": "表示", "pinyin": "biǎoshì", "definition": "to express, indicate"},
    {"hanzi": "表演", "pinyin": "biǎoyǎn", "definition": "performance, to perform"},
    {"hanzi": "宾馆", "pinyin": "bīnguǎn", "definition": "hotel"}
  ]
};
